### ISSUE TITLE
Contact Form Text Area 

### ISSUE THREAD

**Issue by CaoBeee** [CaoBeee/CA-PHE#1]
## Describe the bug
The text input in the text area is starting in the middle of the area rather than the beginning.

### Steps to reproduce
Try to type in the text area.

### Expected behavior
Text starting at the top-left of the text area.

**Comment by Spencer-Breding** [comment]
Works as expected now. Also has text wrapping and vertical scrolling enabled if input gets too long.
![image](https://github.com/CaoBeee/CA-PHE/assets/55817041/2bdb4690-5f3a-4d4a-b418-af199e459846)
